logging:
  level:
    root: DEBUG
    sun.rmi: ERROR
    javax.management.remote.rmi: ERROR

spring:
  datasource:
    services:
      jdbc-url: ${mysqlurlS}
      username: ${mysqlusername}
      password: ${mysqlpassword}

      driver-class-name: com.mysql.cj.jdbc.Driver

    transac:
      jdbc-url: ${mysqlurlT}
      username: ${mysqlusername}
      password: ${mysqlpassword}

      driver-class-name: com.mysql.cj.jdbc.Driver

  security:
    oauth2:
      resourceserver:
        jwt:
          public-key: |
            -----BEGIN PUBLIC KEY-----
            MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAy6eChzB1qkuEXAMPLE
            KEYHEREkDJf1+N6cd0eP6Y/ViZ6KPMmr7P3D6dP3WRAGgkhQIDAQAB
            -----END PUBLIC KEY-----

  jackson:
    deserialization:
      FAIL_ON_UNKNOWN_PROPERTIES: true






