logging:
  level:
    root: DEBUG
    sun.rmi: ERROR
    javax.management.remote.rmi: ERROR

spring:
  config:
    import: "application-password.yaml"

  datasource:
    services:
      jdbc-url: jdbc:mysql://bd1.masmzi.icu:3306/dbservices
      username: api
      driver-class-name: com.mysql.cj.jdbc.Driver

    transac:
      jdbc-url: jdbc:mysql://bd1.masmzi.icu:3306/dbtransac
      username: api
      driver-class-name: com.mysql.cj.jdbc.Driver




