logging:
  level:
    root: DEBUG
    sun.rmi: ERROR
    javax.management.remote.rmi: ERROR

spring:
  config:
    import: "application-password.yaml"

  datasource:
    services:
      jdbc-url: jdbc:mysql://localhost:3306/dbservices
      username: masi
      driver-class-name: com.mysql.cj.jdbc.Driver

    transac:
      jdbc-url: jdbc:mysql://localhost:3306/dbtransac
      username: masi
      driver-class-name: com.mysql.cj.jdbc.Driver
    jpa:
      properties:
        hibernate:
          dialect: org.hibernate.dialect.MySQL8.Dialect