logging:
  level:
    root: DEBUG
    sun.rmi: ERROR
    javax.management.remote.rmi: ERROR

spring:
  datasource:
    services:
      jdbc-url: ${mysqlurlS}
      username: ${mysqlusername}
      password: ${mysqlpassword}

      driver-class-name: com.mysql.cj.jdbc.Driver

    transac:
      jdbc-url: ${mysqlurlT}
      username: ${mysqlusername}
      password: ${mysqlpassword}

      driver-class-name: com.mysql.cj.jdbc.Driver

  jackson:
    deserialization:
      FAIL_ON_UNKNOWN_PROPERTIES: true






