name: Java CI with Maven

on:
  push:
    branches: [ main, Test_final ] # Déclenche sur push vers main ou Test_final
  pull_request:
    branches: [ main, Test_final ] # Déclenche sur pull requests vers main ou Test_final

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        ref: Test_final # Force le checkout de la branche Test_final pour exécuter les tests

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17' # Ajustez selon la version de Java utilisée
        distribution: 'temurin'

    - name: Cache Maven dependencies
      uses: actions/cache@v4
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-

    - name: Run tests with Maven
      run: mvn -B test --file pom.xml # Exécute uniquement les tests